# Matrix manipulation in Python

In [1]:
!pip install numpy

  Using cached numpy-2.1.2-cp310-cp310-macosx_14_0_arm64.whl (5.4 MB)

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
# 1. Create a 3x3 matrix
matrix_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix_A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
matrix_B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
matrix_sum = matrix_A + matrix_B
print(matrix_sum)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [5]:
# 3. Perform matrix multiplication
matrix_product = np.dot(matrix_A, matrix_B)
print(matrix_product)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [6]:
# 4. Find the transpose of a matrix
matrix_transpose = np.transpose(matrix_A)
print(matrix_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
# 5. Find the determinant of a matrix
matrix_det = np.linalg.det(matrix_A)
print(matrix_det)

-9.51619735392994e-16
